version: 1
default_environment: dev
project_id: 3ac50c18-a099-4e52-854f-2835a667e40f

environments:
- name: dev
- name: prod

plugins:
  extractors:
  - name: tap-btg
    namespace: tap_btg
    pip_url: git+https://github.com/felippecaso/tap-btg.git
    settings:
    - name: file_password
    config:
      files:
      - path: s3://felippe-data/raw/btg-investments/
        type: investments_transactions
      - path: s3://felippe-data/raw/btg-credit/
        type: credit_transactions
      - path: s3://felippe-data/raw/btg-banking/
        type: banking_transactions

  - name: tap-nomad
    namespace: tap_nomad
    pip_url: git+https://github.com/felippecaso/tap-nomad.git
    config:
      files:
      - path: s3://felippe-data/raw/nomad/

  - name: tap-spreadsheets-anywhere
    variant: ets
    pip_url: git+https://github.com/ets/tap-spreadsheets-anywhere.git@main
  - name: tap-csv-caju
    inherit_from: tap-spreadsheets-anywhere
    config:
      tables:
      - path: s3://felippe-data
        name: caju_transactions
        pattern: raw/caju/.*csv
        start_date: '2000-01-01T00:00:00Z'
        key_properties: []
        format: csv

  - name: tap-csv-alelo
    inherit_from: tap-spreadsheets-anywhere
    config:
      tables:
      - path: s3://felippe-data
        name: alelo_transactions
        pattern: raw/alelo/.*csv
        start_date: '2000-01-01T00:00:00Z'
        key_properties: []
        format: csv

  - name: tap-csv-bb
    inherit_from: tap-spreadsheets-anywhere
    config:
      tables:
      - path: s3://felippe-data
        name: bb_transactions
        pattern: raw/bb/.*csv
        start_date: '2000-01-01T00:00:00Z'
        key_properties: []
        format: csv
        encoding: latin1

  - name: tap-csv-c6
    inherit_from: tap-spreadsheets-anywhere
    config:
      tables:
      - path: s3://felippe-data
        name: c6_transactions
        pattern: raw/c6/.*csv
        start_date: '2000-01-01T00:00:00Z'
        key_properties: []
        format: csv

  - name: tap-csv-nubank
    inherit_from: tap-spreadsheets-anywhere
    config:
      tables:
      - path: s3://felippe-data
        name: nubank_transactions
        pattern: raw/nubank/.*csv
        start_date: '2000-01-01T00:00:00Z'
        key_properties: []
        format: csv

  - name: tap-csv-itau
    inherit_from: tap-spreadsheets-anywhere
    config:
      tables:
      - path: s3://felippe-data
        name: itau_transactions
        pattern: raw/itau/.*csv
        start_date: '2000-01-01T00:00:00Z'
        key_properties: []
        format: csv
        delimiter: ;

  loaders:
  - name: target-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/target-csv.git
    config:
      output_path_prefix: ./data/catalog/
      overwrite_behavior: replace_file

  - name: target-duckdb
    variant: jwills
    pip_url: target-duckdb~=0.6
    config:
      path: 'md:'
      default_target_schema: meltano
      primary_key_required: false

  transformers:
  - name: dbt-duckdb
    variant: jwills
    pip_url: dbt-core~=1.4.0 dbt-duckdb~=1.4.0 pandas textblob
    config:
      path: $MELTANO_PROJECT_ROOT/data/catalog/qsmds.duckdb
      project_dir: $MELTANO_PROJECT_ROOT/transform

  utilities:
  - name: jupyterlab
    namespace: jupyterlab
    pip_url: jupyterlab jupysql pandas duckdb duckdb-engine label_studio_sdk
    executable: jupyter
    commands:
      launch:
        args: lab
        description: Start lab server
      execute-label-studio-setup:
        args: nbconvert --to notebook --execute notebook/label_studio_setup.ipynb
        description: Execute label_studio_setup notebook
    env:
      DATABASE_URL: duckdb:///../data/catalog/qsmds.duckdb

  - name: label-studio
    namespace: label_studio
    pip_url: label-studio label-studio-sdk
    executable: label-studio
    commands:
      init:
        args: init qs-mds --data-dir $MELTANO_PROJECT_ROOT/label-studio --username
          admin@labelstudio.com --password password
        description: Initialize Label Studio project
      start:
        args: start qs-mds --data-dir $MELTANO_PROJECT_ROOT/label-studio
        description: Start Label Studio

    env:
      LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED: 'true'
      LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT: $MELTANO_PROJECT_ROOT/data/label-studio
      EXPERIMENTAL_FEATURES: 'true'

  mappers:
  - name: meltano-map-transformer
    variant: meltano
    pip_url: git+https://github.com/MeltanoLabs/meltano-map-transform.git
    mappings:
    - name: itau_transactions_mapper
      config:
        stream_maps:
          itau_transactions:
            date: datetime.datetime.strptime(date, '%d/%m/%Y')
            amount: amount.replace(',', '.')
            __filter__: ('SALDO' not in description) and ('APL APLIC' not in description)
              and ('RES APLIC' not in description)
    - name: nubank_transactions_mapper
      config:
        stream_maps:
          nubank_transactions:
            date: datetime.datetime.fromisoformat(date)
            description: title
            target_category: category
            title: __NULL__
            category: __NULL__
    - name: c6_transactions_mapper
      config:
        stream_maps:
          c6_transactions:
            date: datetime.datetime.fromisoformat(date)
            description: title
            title: __NULL__
    - name: bb_transactions_mapper
      config:
        stream_maps:
          bb_transactions:
            date: datetime.datetime.strptime(data, "%d/%m/%Y")
            amount: valor
    - name: alelo_transactions_mapper
      config:
        stream_maps:
          alelo_transactions:
            description: title
            date: datetime.datetime.fromisoformat(date)
            title: __NULL__
    - name: caju_transactions_mapper
      config:
        stream_maps:
          caju_transactions:
            status: status
            date: data
            amount: valor
            action: record['ação']
            action_type: record['tipo_de_ação']
            target_category: record['categoria_destino']
            vendor: estabelecimento
            deal_id: deal_id
            _smart_source_bucket: _smart_source_bucket
            _smart_source_file: _smart_source_file
            _smart_source_lineno: _smart_source_lineno
            __else__: __NULL__
            __filter__: status == 'Completo'
    - name: nomad_transactions_mapper
      config:
        stream_maps:
          nomad_transactions:
            __filter__: status == 'Concluído'
    - name: btg_mapper
      config:
        stream_maps:
          btg_investments_transactions:
            __filter__: description != 'Rendimento Disponível - Saldo Remunerado'

jobs:
- name: load-finances-to-duckdb
  tasks:
  - tap-csv-caju caju_transactions_mapper target-duckdb
  - tap-csv-alelo alelo_transactions_mapper target-duckdb
  - tap-csv-bb bb_transactions_mapper target-duckdb
  - tap-csv-c6 c6_transactions_mapper target-duckdb
  - tap-csv-nubank nubank_transactions_mapper target-duckdb
  - tap-csv-itau itau_transactions_mapper target-duckdb
  - tap-btg btg_mapper target-duckdb
  - tap-nomad nomad_transactions_mapper target-duckdb
- name: load-finances-to-csv
  tasks:
  - tap-csv-caju caju_transactions_mapper target-csv
  - tap-csv-alelo alelo_transactions_mapper target-csv
  - tap-csv-bb bb_transactions_mapper target-csv
  - tap-csv-c6 c6_transactions_mapper target-csv
  - tap-csv-nubank nubank_transactions_mapper target-csv
  - tap-csv-itau itau_transactions_mapper target-csv
  - tap-btg btg_mapper target-csv
  - tap-nomad nomad_transactions_mapper target-csv
schedules:
- name: weekly-finances-load
  interval: '@weekly'
  job: load-finances-to-csv
