version: 1
default_environment: dev
project_id: 3ac50c18-a099-4e52-854f-2835a667e40f

environments:
- name: dev
- name: staging
- name: prod

plugins:
  extractors:
  - name: tap-btg
    namespace: tap_btg
    pip_url: git+https://github.com/felippecaso/tap-btg.git
    config:
      files:
      - path: ./data/raw/btg_investments
        type: investments_transactions
      - path: ./data/raw/btg_credit
        type: credit_transactions
      - path: ./data/raw/btg_banking
        type: banking_transactions
  - name: tap-nomad
    namespace: tap_nomad
    pip_url: git+https://github.com/felippecaso/tap-nomad.git
    config:
      files:
      - path: ./data/raw/nomad
  - name: tap-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-csv.git
    config:
      files:
      - path: ./data/raw/caju
        entity: caju_transactions
        keys: []
      - path: ./data/raw/alelo
        entity: alelo_transactions
        keys: []
      - path: ./data/raw/bb
        entity: bb_transactions
        keys: []
        encoding: latin-1
      - path: ./data/raw/c6
        entity: c6_transactions
        keys: []
      - path: ./data/raw/nubank
        entity: nubank_transactions
        keys: []

  loaders:
  - name: target-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/target-csv.git
    config:
      output_path_prefix: ./data/catalog/
      overwrite_behavior: replace_file

  transformers:
  - name: dbt-duckdb
    variant: jwills
    pip_url: dbt-core~=1.4.0 dbt-duckdb~=1.4.0
    config:
      path: $MELTANO_PROJECT_ROOT/data/catalog/qsmds.db
      schema: main
      project_dir: $MELTANO_PROJECT_ROOT/transform
jobs:
- name: load-finances
  tasks:
  - tap-csv target-csv
  - tap-btg target-csv
  - tap-nomad target-csv
