name: qsmds
version: '0.1.0'
config-version: 2

profile: meltano

model-paths: ["models"]
target-path: ../.meltano/transformers/dbt/target
log-path: logs

packages-install-path: dbt_packages

clean-targets:
- ../.meltano/transformers/dbt/target
- dbt_packages
- logs

models:
  qsmds:
    staging:
      +materialized: ephemeral
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: external
      +format: parquet